CREATE TABLE IDIOMAS (
	ID INTEGER NOT NULL PRIMARY KEY ASC,
	NOMBRE TEXT NOT NULL UNIQUE,
	LETRAS INTEGER NOT NULL,
	LETRAS_DISTINTAS INTEGER NOT NULL,
	PALABRAS INTEGER NOT NULL,
	PALABRAS_DISTINTAS INTEGER NOT NULL,
	SIGNOS INTEGER NOT NULL, 
	SIGNOS_DISTINTOS INTEGER NOT NULL,
	SIMBOLOS INTEGER NOT NULL,
	SIMBOLOS_DISTINTOS NOT NULL
);

CREATE TABLE IDIOMAS_LETRAS (
	IDIOMA_ID INTEGER NOT NULL REFERENCES IDIOMAS(ID),
	LETRA_ID INTEGER NOT NULL,
	CANTIDAD INTEGER NOT NULL,
	PORCENTAJE REAL NOT NULL,
	TIPO INTEGER NOT NULL CHECK (TIPO IN (1, 2, 3)),
	PRIMARY KEY (IDIOMA_ID ASC, LETRA_ID ASC)
) WITHOUT ROWID;

CREATE TABLE IDIOMAS_PALABRAS (
	IDIOMA_ID INTEGER NOT NULL REFERENCES IDIOMAS(ID),
	PALABRA TEXT NOT NULL,
	CANTIDAD INTEGER NOT NULL,
	PORCENTAJE REAL NOT NULL,
	PRIMARY KEY (IDIOMA_ID ASC, PALABRA ASC)
) WITHOUT ROWID;

CREATE TABLE DOCUMENTOS (
	ID INTEGER NOT NULL PRIMARY KEY ASC,
	HASH TEXT NOT NULL,
	LETRAS INTEGER NOT NULL,
	LETRAS_DISTINTAS INTEGER NOT NULL,
	PALABRAS INTEGER NOT NULL,
	PALABRAS_DISTINTAS INTEGER NOT NULL,
	SIGNOS INTEGER NOT NULL, 
	SIGNOS_DISTINTOS INTEGER NOT NULL,
	SIMBOLOS INTEGER NOT NULL,
	SIMBOLOS_DISTINTOS NOT NULL,
	IDIOMA_ID INTEGER NULL REFERENCES IDIOMAS(ID), 
	CONFIANZA REAL NULL
);

CREATE TABLE DOCUMENTOS_LETRAS (
	DOCUMENTO_ID INTEGER NOT NULL REFERENCES DOCUMENTOS(ID),
	LETRA_ID INTEGER NOT NULL,
	CANTIDAD INTEGER NOT NULL,
	PORCENTAJE REAL NOT NULL,
	TIPO INTEGER NOT NULL CHECK (TIPO IN (1, 2, 3)),
	PRIMARY KEY (DOCUMENTO_ID ASC, LETRA_ID ASC)
) WITHOUT ROWID;

CREATE TABLE DOCUMENTOS_PALABRAS (
	DOCUMENTO_ID INTEGER NOT NULL REFERENCES DOCUMENTOS(ID),
	PALABRA TEXT NOT NULL,
	CANTIDAD INTEGER NOT NULL,
	PORCENTAJE REAL NOT NULL,
	PRIMARY KEY (DOCUMENTO_ID ASC, PALABRA ASC)
) WITHOUT ROWID;

CREATE INDEX DOCUMENTOS_HASHES ON DOCUMENTOS (HASH, PALABRAS_DISTINTAS);